export const COOLING_RESPONSE_COMMANDS = [
  "AUTONOMY:FAN_ON",
  "AUTONOMY:AERO_OPEN",
  "AUTONOMY:THROTTLE_SCALE:0.90",
] as const;

export const COOLING_RECOVERY_COMMANDS = [
  "AUTONOMY:FAN_OFF",
] as const;

export const EXHAUST_CLEANOUT_COMMANDS = [
  "AUTONOMY:THROTTLE_BOOST:1.10",
  "AUTONOMY:ENGINE_CLEAN_BURN",
  "AUTONOMY:THROTTLE_SCALE:1.05",
] as const;

export const BATTERY_PROTECTION_COMMANDS = [
  "AUTONOMY:LOAD_SHED",
  "AUTONOMY:SHUTDOWN_NONCRITICAL",
  "AUTONOMY:REDUCE_AERO_LOAD",
] as const;

export const RPM_ADVISORY_COMMANDS = [
  "AUTONOMY:SHIFT_UP",
  "AUTONOMY:THROTTLE_LIMIT:0.95",
  "AUTONOMY:ENGINE_SAFETY_HOLD",
] as const;

export const AUTONOMY_DEFAULT_COMMANDS = Array.from(
  new Set([
    ...COOLING_RESPONSE_COMMANDS,
    ...COOLING_RECOVERY_COMMANDS,
    ...EXHAUST_CLEANOUT_COMMANDS,
    ...BATTERY_PROTECTION_COMMANDS,
    ...RPM_ADVISORY_COMMANDS,
  ]),
);
